equation_processor =design_framework/equationProcessor.php

default:
	#php ${equation_processor} --source="./equations.php" --jsonOutputFile="./parameters-<id>.json" --solidworksOutputFile="./parameters-<id>.solidworksEquations"
	# php ${equation_processor} --source="./equations.php" --jsonOutputFile="./parameters-<id>.json"
	#php ${equation_processor} --source="./equations.php" --jsonOutputFile="./parameters-<id>.json" --updateClassInstances=true --prototypesPath="./prototypes" --classInstancesPath="." 
	php ${equation_processor} --source="./equations.php" --jsonOutputFile="./parameters-<id>.json"  